import Head from 'next/head'
import Script from 'next/script'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { Inputcreate, InputDelete, Inputjoin } from '../components/input'
import SalaVideo from './sala'

export default function Home() {

  const [sala, setSala] = useState("")

  return (
    <div className={styles.container}>
      <Head>
        {sala.length !== 13 &&
          <title>Home</title>
        }
        {sala.length === 13 &&
          <title>Sala Compartida</title>
        }
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossOrigin="anonymous"></link>
      </Head>

      {sala.length !== 13 &&
      <main className={styles.main}>
          <h3>Bienvenido, usuario, te explico rapidamente como funciona mi app</h3>
          <h5>Deberas ingresar una URL de youtube para crear una sala, pasar el Code a tus amigos y ellos podran entrar</h5>
          <h5>Uno de ustedes sera el responsable de manejar el video para todos los demas, a excepcion de la resolucion y cc</h5>
          <h5>Tendran un Chat donde podran comentarse entre ustedes acerca del video </h5>
          <h5>Y comentarle al Host si quieren menos, mas volumen si quieren que adelante o retroceda el video</h5>
          <h5>Si tienes algun problema con una sala puedes introducir el Code en delete, crearla y disfrutar con tus amigos</h5>
          <Inputcreate setSala={setSala} />
          <Inputjoin setSala={setSala} />
          <InputDelete />
      </main>
      }

      {sala.length === 13 &&
        <SalaVideo room={sala} />
      }    

      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossOrigin="anonymous"></Script>
    </div>
  )
}
